"""
builders/pages.py — Static page builder.

Renders every entry in the PAGES manifest to ``dist/``.
Each static page template receives full CMS data so any page
can display dynamic content (e.g. the homepage shows recent posts).

Work section note
-----------------
The static ``work/overview.html`` template is intentionally excluded
from the PAGES manifest.  The /work/ page is now generated by
``builders/work.py`` from live Sanity data.

The individual static work detail pages (e.g. work/anthology-*.html)
remain in the PAGES manifest and continue to build as-is.  They will
be replaced one-by-one as editors migrate content into Sanity.
"""

import logging
import os
from typing import Any

from jinja2 import Environment

from config import DIST_DIR
from helpers.seo import build_seo_context
from helpers.i18n import LOCALES, load_locale, prefix_url

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Page manifest
# ---------------------------------------------------------------------------
# (template_path_relative_to_pages, url_path)
# url_path is the directory relative to dist/ that will contain index.html.
# An empty string means the root: dist/index.html
#
# NOTE: "work/overview.html" / "work" is intentionally absent.
# /work/ is now generated by builders/work.py.
# Static work detail pages remain here until migrated to Sanity.
PAGES: list[tuple[str, str]] = [
    ("home/index.html",                                         ""),
    ("about/overview.html",                                     "about"),
    ("lets-talk/overview.html",                                 "lets-talk"),
    ("resources/overview.html",                                 "resources"),
    # EdTech Marketing — Santiago design (new pages, never existed before)
    ("edtech-marketing-agency/index.html",          "edtech-marketing-agency"),
    ("edtech-marketing-agency/practice/index.html", "edtech-marketing-agency/practice"),
    ("edtech-marketing-agency/service/index.html",  "edtech-marketing-agency/service"),
    # NOTE: individual resources/slug pages removed — now generated by
    # builders/posts.py:build_resources() from Sanity via resources/post.html.
    # edtech-mentor-interviews/ is generated by MentorBuilder from Sanity.
]


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------

def build_pages(
    env: Environment,
    posts: list[dict[str, Any]] | None = None,
    resources: list[dict[str, Any]] | None = None,
    work: list[dict[str, Any]] | None = None,
    mentors: list[dict[str, Any]] | None = None,
    settings: dict[str, Any] | None = None,
    testimonials: list[dict[str, Any]] | None = None,
    clients: list[dict[str, Any]] | None = None,
    practices: list[dict[str, Any]] | None = None,
    team: list[dict[str, Any]] | None = None,
) -> int:
    """
    Render all static page templates and write them to dist/.

    For each locale in helpers.i18n.LOCALES the entire PAGES list is
    rendered again with:
      - i18n context (nav labels, locale metadata)
      - nav_prefix ("/eu", "/es", or "")
      - current_path (for the language switcher to build alternate URLs)
      - hreflang_links in the SEO context

    The canonical (en-us) locale writes to dist/ directly.
    Additional locales write to dist/{prefix}/.

    Parameters
    ----------
    env:
        Configured Jinja2 environment.
    posts:
        List of post dicts from Sanity.
    resources:
        List of resource dicts from Sanity.
    work:
        List of work project dicts from Sanity.
    mentors:
        List of interview dicts from Sanity (EdTech Mentor).
    settings:
        Global site settings dict from Sanity singleton.
    testimonials:
        List of featured testimonial dicts for the home slider.
    clients:
        List of featured client dicts for the home logo strip.
    practices:
        List of practice dicts for the home pcard and agency page.
    team:
        List of active team member dicts for the About page.

    Returns
    -------
    int
        Number of pages built (across all locales).
    """
    posts        = posts        or []
    resources    = resources    or []
    work         = work         or []
    mentors      = mentors      or []
    settings     = settings     or {}
    testimonials = testimonials or []
    clients      = clients      or []
    practices    = practices    or []
    team         = team         or []
    count = 0

    for loc in LOCALES:
        locale_prefix = loc["prefix"]       # "" | "eu" | "es"
        nav_prefix    = f"/{locale_prefix}" if locale_prefix else ""
        i18n          = load_locale(loc["key"])

        for template_path, url_path in PAGES:
            try:
                template = env.get_template(template_path)
            except Exception as exc:
                logger.error("Could not load template %r: %s", template_path, exc)
                continue

            # Locale-prefixed url_path for dist/ directory
            localized_url = prefix_url(url_path, locale_prefix)

            # SEO context — pass neutral path so hreflang covers all locales
            _og_locale_map = {"en-us": "en_US", "en-eu": "en_GB", "es-419": "es_419"}
            seo = build_seo_context(
                url_path=localized_url,
                url_path_neutral=url_path,
                locale=i18n.get("lang", "en"),
                og_locale=_og_locale_map.get(loc["key"], "en_US"),
            )

            # current_path: the absolute URL path for THIS locale's page,
            # used by the language switcher to build alternate hrefs.
            current_path = f"/{localized_url}/" if localized_url else "/"

            try:
                html = template.render(
                    posts=posts,
                    resources=resources,
                    work=work,
                    mentors=mentors,
                    settings=settings,
                    testimonials=testimonials,
                    clients=clients,
                    practices=practices,
                    team=team,
                    seo=seo,
                    i18n=i18n,
                    nav_prefix=nav_prefix,
                    current_path=current_path,
                    neutral_path=url_path,
                    hreflang_links=seo["hreflang_links"],
                )
            except Exception as exc:
                logger.error("Error rendering %r (%s): %s", template_path, loc["key"], exc)
                continue

            if localized_url:
                out_dir = os.path.join(DIST_DIR, localized_url)
            else:
                out_dir = DIST_DIR
            os.makedirs(out_dir, exist_ok=True)

            out_path = os.path.join(out_dir, "index.html")
            with open(out_path, "w", encoding="utf-8") as fh:
                fh.write(html)

            label = f"/{localized_url}/" if localized_url else "/"
            logger.info("  built %s [%s]", label, loc["key"])
            count += 1

    return count
